services:
  - type: web
    name: football-ai-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_FOOTBALL_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
    plan: free
    autoDeploy: true

  - type: cron
    name: scan-live
    schedule: "*/5 * * * *"
    path: /tasks/scan-live
    method: GET

  - type: cron
    name: scan-upcoming
    schedule: "0 * * * *"
    path: /tasks/scan-upcoming
    method: GET

  - type: cron
    name: cleanup
    schedule: "0 0 * * *"
    path: /tasks/cleanup
    method: GET

  - type: cron
    name: daily-summary
    schedule: "0 21 * * *"
    path: /tasks/daily-summary
    method: GET
