services:
  - type: web
    name: Goalsniper-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT server:app --workers 1 --threads 4 --timeout 120
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: API_KEY
        sync: false
    plan: free
    autoDeploy: true
