services:
  # ------------------------------------------------------
  # MAIN LIVE PREDICTION SERVICE
  # ------------------------------------------------------
  goalsniper:
    build:
      dockerfile: Dockerfile
    env:
      PORT: 8000
      ENVIRONMENT: "production"
      SAFE_MODE: "true"        # set TRUE until real models train
    healthcheck:
      path: /health
      interval: 10
      timeout: 4
      retries: 3
    deploy:
      restart_policy: always
      resources:
        cpu: 1
        memory: 1024
    start: "python main.py"

  # ------------------------------------------------------
  # TRAINING SERVICE (CRON JOB)
  # ------------------------------------------------------
  train-models:
    build:
      dockerfile: Dockerfile
    env:
      ENVIRONMENT: "production"
    start: "python train_models.py"

    # Daily at 02:00 UTC (04:00 winter Berlin, 05:00 summer)
    schedule:
      cron: "0 2 * * *"

    deploy:
      resources:
        cpu: 1
        memory: 1024

  resolve-results:
    build:
      dockerfile: Dockerfile
    env:
      ENVIRONMENT: "production"
    start: "python resolve_results.py"
    schedule:
      cron: "*/30 * * * *"   # every 30 minutes
    deploy:
      resources:
        cpu: 0.5
        memory: 512

  log-roi:
    build:
      dockerfile: Dockerfile
    env:
      ENVIRONMENT: "production"
    start: "python log_roi.py"
    schedule:
      cron: "5 0 * * *"      # daily at 00:05 UTC
    deploy:
      resources:
        cpu: 0.5
        memory: 256

  update-strength:
    build:
      dockerfile: Dockerfile
    env:
      ENVIRONMENT: "production"
    start: "python update_team_strength.py"
    schedule:
      cron: "10 0 * * *"     # daily at 00:10 UTC
    deploy:
      resources:
        cpu: 0.5
        memory: 512
