services:
  goalsniper:
    build:
      dockerfile: Dockerfile
    env:
      PORT: 8000
    healthcheck:
      path: /health
      interval: 10
      timeout: 4
      retries: 3
    deploy:
      restart_policy: always
      resources:
        cpu: 1
        memory: 1024
    start: "python main.py"

  train-models:
    build:
      dockerfile: Dockerfile
    env:
      ENVIRONMENT: "production"
    start: "python train_models.py"
    schedule:
      cron: "0 4 * * 1"     # every Monday 04:00 UTC
    deploy:
      resources:
        cpu: 1
        memory: 1024
