# Railway service config for a FastAPI app served by Gunicorn+Uvicorn
# Assumes your ASGI app is at app/main.py with variable `app`
# i.e. import path: app.main:app
services:
  web:
    build:
      builder: "NIXPACKS"
      buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: >
      gunicorn app.main:app
      -k uvicorn.workers.UvicornWorker
      -w ${WEB_CONCURRENCY:-2}
      -b 0.0.0.0:${PORT}
      --timeout 60
      --graceful-timeout 30
      --keep-alive 5
      --log-level ${LOG_LEVEL:-info}
    env:
      PYTHONUNBUFFERED: "1"
      PORT: "8000"           # Railway will override with its assigned port
      WEB_CONCURRENCY: "2"   # tune up/down depending on CPU
      LOG_LEVEL: "info"
    healthcheck:
      path: "/health"
      interval: 10
      timeout: 3
      retries: 3
