# Railway config for Goalsniper (FastAPI via Gunicorn+Uvicorn)
services:
  web:
    build:
      builder: "NIXPACKS"
      buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: >
      gunicorn goalsniper.server:app
      -k uvicorn.workers.UvicornWorker
      -w ${WEB_CONCURRENCY:-1}
      -b 0.0.0.0:${PORT}
      --timeout 120
      --graceful-timeout 20
      --log-level ${LOG_LEVEL:-info}
    env:
      PYTHONUNBUFFERED: "1"
      LOG_LEVEL: "info"
      # DB_PATH should point to a persistent volume mounted at /data
      DB_PATH: "/data/goalsniper.db"
      TZ: "UTC"
    healthcheck:
      path: "/health"
      interval: 10
      timeout: 3
      retries: 3

  cron:
    build:
      builder: "NIXPACKS"
      buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "python -m goalsniper.run_once"
    schedule: "0 * * * *"   # hourly
    env:
      PYTHONUNBUFFERED: "1"
      DB_PATH: "/data/goalsniper.db"
      TZ: "UTC"
