# railway.yaml
services:
  api:
    build:
      builder: python:3.11
      buildCommand: pip install --no-cache-dir -r requirements.txt
      startCommand: python main.py

  trainer:
    build:
      builder: python:3.11
      buildCommand: pip install --no-cache-dir -r requirements.txt
      startCommand: python train_models.py --db-url $DATABASE_URL
