services:
  - type: web
    name: goalsniper
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn goalsniper.server:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
    envVars:
      # use the name the code expects; or keep both to be safe
      - key: API_KEY
        sync: false
      - key: APISPORTS_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: RUN_TOKEN
        generateValue: true
      - key: TELEGRAM_WEBHOOK_TOKEN
        generateValue: true
      - key: DB_PATH
        value: "/data/goalsniper.db"
      - key: SCAN_DAYS
        value: "1"
      - key: MAX_CONCURRENT_REQUESTS
        value: "6"
      - key: STATS_REQUEST_DELAY_MS
        value: "200"
      - key: MAX_TIPS_PER_RUN
        value: "150"
      - key: MIN_CONFIDENCE_TO_SEND
        value: "0.58"
      - key: LIVE_ENABLED
        value: "true"
      - key: LIVE_MINUTE_MIN
        value: "10"
      - key: LIVE_MINUTE_MAX
        value: "85"
      - key: LIVE_MAX_FIXTURES
        value: "80"
      - key: TZ
        value: "UTC"

  - type: cron
    name: goalsniper-cron
    plan: free
    schedule: "0 * * * *"   # hourly
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m goalsniper.run_once"
    envVars:
      - key: API_KEY
        sync: false
      - key: APISPORTS_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: DB_PATH
        value: "/data/goalsniper.db"
      - key: SCAN_DAYS
        value: "1"
      - key: MAX_CONCURRENT_REQUESTS
        value: "6"
      - key: STATS_REQUEST_DELAY_MS
        value: "200"
      - key: MAX_TIPS_PER_RUN
        value: "150"
      - key: MIN_CONFIDENCE_TO_SEND
        value: "0.58"
      - key: LIVE_ENABLED
        value: "false"
      - key: TZ
        value: "UTC"
